[Release3] Merging code to master branch for release3.
eclipse-tractusx/dft-backend pull request #8
Opened 2023-01-20 10:53 UTC by adityagajbhiye

HotFix Scan issues has been fixed.

2023-01-24 14:30 UTC, Siegfriedk commented on modules/sde-core/src/main/resources/flyway/V15__Alter_Tables.sql
> + * Copyright (c) 2022 Contributors to the CatenaX (ng) GitHub Organisation
You are mixxing catenax and eclipse foundation here. Please fix this

2023-01-24 14:52 UTC, carslen requested changes
Please ensure that all source code filed have a license header added. I've stopped checking every file for an existing header.

2023-01-24 14:52 UTC, carslen commented on modules/sde-core/src/test/java/org/eclipse/tractusx/sde/core/controller/SubmodelCsvControllerTest.java
> +package org.eclipse.tractusx.sde.core.controller;
License header missing

2023-01-24 14:52 UTC, carslen commented on modules/sde-submodules/batch/src/main/java/org/eclipse/tractusx/sde/submodels/batch/BatchExecutor.java
>  import org.eclipse.tractusx.sde.common.submodel.executor.create.steps.impl.JsonRecordValidate;
License header missing

2023-01-24 14:52 UTC, carslen commented on modules/sde-submodules/batch/src/main/java/org/eclipse/tractusx/sde/submodels/batch/BatchSubmodel.java
>  		submodel = loadSubmodel(input);
License header missing

2023-01-24 14:52 UTC, carslen commented on modules/sde-submodules/batch/src/main/java/org/eclipse/tractusx/sde/submodels/batch/service/BatchService.java
License header missing

2023-01-25 07:11 UTC, adityagajbhiye commented on modules/sde-core/src/test/java/org/eclipse/tractusx/sde/core/controller/SubmodelCsvControllerTest.java
> +package org.eclipse.tractusx.sde.core.controller;
We have updated License header.

2023-01-25 07:12 UTC, adityagajbhiye commented on modules/sde-submodules/batch/src/main/java/org/eclipse/tractusx/sde/submodels/batch/BatchExecutor.java
>  import org.eclipse.tractusx.sde.common.submodel.executor.create.steps.impl.JsonRecordValidate;
We have updated License header.

2023-01-25 07:12 UTC, adityagajbhiye commented on modules/sde-submodules/batch/src/main/java/org/eclipse/tractusx/sde/submodels/batch/BatchSubmodel.java
>  		submodel = loadSubmodel(input);
We have updated License header.

2023-01-25 07:12 UTC, adityagajbhiye commented on modules/sde-submodules/batch/src/main/java/org/eclipse/tractusx/sde/submodels/batch/service/BatchService.java
We have updated License header.

2023-01-25 08:21 UTC, carslen approved these changes
LGTM, wait for @SiegfriedK OK

2023-01-25 14:22 UTC, merged